steps:
  - command: echo test artifact still uploaded > art
    label: PR version
    plugins:
      - https://github.com/arturopie/docker-compose-buildkite-plugin#267-move-compose-cleanup-to-pre-artifact:
          run: app
  - command: echo test artifact still uploaded > art
    label: original version
    plugins:
      - docker-compose#v3.9.0:
          run: app
